"""Fingerprint-Datenbank selbstgehosteter Apps fuer Periscan.

Auto-generiert aus verifizierter Multi-Agent-Recherche (62 Apps, exposure_checks fuer 50 Apps).
Felder: app, category, risk, intended_public, titles, servers, headers,
        body_markers, login_paths, exposure_checks.
"""

FINGERPRINTS = [
    {
        "app": 'AdGuard Home', "category": 'DNS-Adblocker (Netzwerk-Admin)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['adguard home'],
        "servers": ['AdGuardHome'],
        "headers": ['server: AdGuardHome'],
        "body_markers": ['adguard home', '/control/', '__webpack_public_path__'],
        "login_paths": ['/control/login', '/login.html', '/control/status'],
        "exposure_checks": [{'path': '/control/status', 'status': 200, 'body_contains': ['"dns_addresses"', '"protection_enabled"', '"version"'], 'proves': '/control/status returns AdGuard Home version, DNS listen addresses and protection state; on a configured instance this requires auth (403/401 to anonymous), so a real-data 200 means the instance is exposed and leaking config.', 'risk': 'MEDIUM'}, {'path': '/control/install/get_addresses', 'status': 200, 'body_contains': ['"interfaces"', '"dns_port"', '"web_port"'], 'proves': 'The first-run install wizard endpoint answers with data (post-setup it returns 403), meaning AdGuard Home has no admin account yet; the install flow lets anyone set the admin credentials (unauth account takeover).', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Adminer', "category": 'DB-Admin (Multi-DB, Single-File PHP)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['adminer', 'login - adminer'],
        "servers": [],
        "headers": [],
        "body_markers": ['name="auth[driver]"', 'name="auth[server]"', 'name="auth[username]"', 'name="auth[password]"', 'name="auth[db]"', 'www.adminer.org', 'id="version"', 'name="auth[permanent]"'],
        "login_paths": ['/', '/adminer.php', '/adminer/'],
    },
    {
        "app": 'Authelia', "category": 'SSO / Auth-Portal (ForwardAuth)',
        "risk": 'LOW', "intended_public": True,
        "titles": ['login - authelia'],
        "servers": [],
        "headers": ['set-cookie: authelia_session'],
        "body_markers": ['data-passkeylogin', 'data-basepath', 'data-rememberme', 'data-resetpassword'],
        "login_paths": ['/api/configuration', '/api/state', '/api/firstfactor'],
        "exposure_checks": [{'path': '/api/state', 'status': 200, 'body_contains': ['"authentication_level"', '"default_redirection_url"'], 'proves': 'The /api/state SPA-bootstrap endpoint is unauthenticated by design; a real-data 200 confirms an internet-reachable Authelia portal and leaks its authentication_level/redirect metadata. authentication_level is the stable distinctive marker (default_redirection_url is version-dependent).', 'risk': 'LOW'}, {'path': '/api/health', 'status': 200, 'body_contains': ['"status":"OK"'], 'proves': '/api/health responds OK without auth, confirming the presence of an Authelia instance at this host.', 'risk': 'INFO'}],
    },
    {
        "app": 'Authentik', "category": 'IdP / SSO (Identity Provider)',
        "risk": 'LOW', "intended_public": True,
        "titles": ['authentik'],
        "servers": [],
        "headers": ['set-cookie: authentik_session', 'x-authentik-version'],
        "body_markers": ['ak-flow-executor', 'ak-stage-identification', 'ak-message-container', '/if/flow/'],
        "login_paths": ['/if/flow/default-authentication-flow/', '/-/health/live/', '/api/v3/root/config/'],
        "exposure_checks": [{'path': '/-/health/ready/', 'status': 204, 'body_contains': [], 'proves': 'The authentik-specific /-/health/ready/ endpoint answers unauthenticated (HTTP 204), distinctively fingerprinting an Authentik deployment and confirming its database backend is up.', 'risk': 'INFO'}, {'path': '/api/v3/root/config/', 'status': 200, 'body_contains': ['"capabilities"', '"branding_title"', '"error_reporting"'], 'proves': 'The authentik /api/v3/root/config/ endpoint returns capabilities, branding and error-reporting config fully unauthenticated, distinctively identifying an exposed Authentik server and leaking its instance configuration surface.', 'risk': 'INFO'}],
    },
    {
        "app": 'Beszel', "category": 'Server-Monitoring (leichtgewichtig)',
        "risk": 'LOW', "intended_public": False,
        "titles": ['beszel'],
        "servers": [],
        "headers": [],
        "body_markers": ['globalThis.BESZEL'],
        "login_paths": ['/', '/_/', '/api/health'],
        "exposure_checks": [{'path': '/api/health', 'status': 200, 'body_contains': ['api is healthy.', '"code":200'], 'proves': "Beszel is built on PocketBase, whose /api/health is unauthenticated and returns 'API is healthy.', confirming an exposed Beszel/PocketBase backend reachable for further enumeration.", 'risk': 'LOW'}],
    },
    {
        "app": 'Caddy', "category": 'Webserver / Reverse-Proxy',
        "risk": 'LOW', "intended_public": True,
        "titles": ['caddy'],
        "servers": ['caddy'],
        "headers": ['server: caddy'],
        "body_markers": ['caddy is ready to serve your site over https', 'your web server is working. now make it work for you', 'congratulations! your web server is working'],
        "login_paths": [],
        "exposure_checks": [{'path': '/config/', 'status': 200, 'body_contains': ['"apps"', '"http"', '"servers"'], 'proves': 'The Caddy admin API (default localhost:2019, unauthenticated by design) is reachable remotely and returns the entire active config; the same unauth API accepts POST to reconfigure routes/TLS, i.e. full unauth control of the proxy when exposed beyond localhost.', 'risk': 'CRITICAL'}, {'path': '/reverse_proxy/upstreams', 'status': 200, 'body_contains': ['"num_requests"', '"fails"', '"address"'], 'proves': 'The admin API upstreams endpoint returns live backend addresses and health stats without auth, proving the Caddy admin API is exposed beyond localhost.', 'risk': 'HIGH'}],
    },
    {
        "app": 'Cockpit', "category": 'Linux server / host admin console',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": ['x-dbus-csrf-token', 'set-cookie: cockpit'],
        "body_markers": ['cockpit/static/login.css', 'cockpit/static/login.js', 'is_cockpit_client', 'please enable javascript to use the web console'],
        "login_paths": ['/', '/cockpit/login', '/cockpit/$login/'],
        "exposure_checks": [{'path': '/ping', 'status': 200, 'body_contains': ['"service":', '"cockpit"'], 'proves': 'Cockpit\'s /ping health endpoint answers without authentication (it is explicitly exempt from auth and even works over plain HTTP) and returns the JSON body {"service":"cockpit"}, proving a Cockpit web console is exposed on this host.', 'risk': 'INFO'}],
    },
    {
        "app": 'code-server', "category": 'Browser-IDE / VS Code im Browser',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['- code-server'],
        "servers": [],
        "headers": ['set-cookie: code-server-session'],
        "body_markers": ['src/browser/pages/login', 'login.css', '/_static/', 'center-container', 'card-box'],
        "login_paths": ['/login', '/'],
        "exposure_checks": [{'path': '/healthz', 'status': 200, 'body_contains': ['"lastheartbeat"'], 'proves': 'code-server health endpoint answers without auth (it is exempt even when the default auth=password is enabled), fingerprinting a code-server instance; it does not by itself prove the editor is unprotected.', 'risk': 'INFO'}],
    },
    {
        "app": 'Dashy', "category": 'Application-Dashboard / Startpage',
        "risk": 'LOW', "intended_public": False,
        "titles": ['dashy'],
        "servers": [],
        "headers": [],
        "body_markers": ['needs to be enabled to run Dashy', 'Lissy93/dashy', '/dashy.css'],
        "login_paths": ['/', '/login'],
        "exposure_checks": [{'path': '/conf.yml', 'status': 200, 'body_contains': ['pageinfo:', 'appconfig:', 'sections:'], 'proves': 'Dashy serves its full configuration file unauthenticated by default; the YAML proves the app and may leak embedded API keys, credentials and internal service URLs.', 'risk': 'HIGH'}, {'path': '/config-manager/save', 'status': 200, 'body_contains': ['success', 'saved'], 'proves': "Dashy's config-manager save endpoint accepts unauthenticated writes with no server-side auth enforcement (preventWriteToDisk is client-side only), allowing an attacker to overwrite the dashboard config (link hijack/phishing, DoS).", 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Docker Registry UI (Joxit)', "category": 'Docker registry browser UI',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['docker registry ui'],
        "servers": [],
        "headers": [],
        "body_markers": ['<docker-registry-ui', 'docker-registry-ui.js'],
        "login_paths": ['/v2/', '/v2/_catalog'],
        "exposure_checks": [{'path': '/v2/_catalog', 'status': 200, 'body_contains': ['"repositories"'], 'proves': 'The backing Docker Registry returns its repository catalog without authentication (registry default is no auth), proving an open registry; image names (and via further /v2 calls, tags and manifests) are enumerable and pullable by anyone.', 'risk': 'HIGH'}, {'path': '/v2/', 'status': 200, 'body_contains': ['{}'], 'proves': 'The registry v2 API base returns 200 with an empty JSON body and no WWW-Authenticate challenge, confirming an unauthenticated Docker Registry backing the Joxit UI (an auth-enabled registry would answer 401 with a Bearer/Basic challenge).', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'Dockge', "category": 'Docker Compose stack manager',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['dockge'],
        "servers": [],
        "headers": [],
        "body_markers": ['src="/src/main.ts"'],
        "login_paths": ['/setup', '/socket.io/'],
        "exposure_checks": [{'path': '/', 'status': 200, 'body_contains': ['dockge', '/socket.io/'], 'proves': 'Serves the Dockge SPA shell (Vue app wiring up its socket.io endpoint) over plain HTTP, confirming an exposed Dockge instance. First-admin creation happens over the WebSocket, so an exposed UI with no users allows unauth admin creation, but that state is only detectable via the socket handshake, not a plain GET.', 'risk': 'INFO'}],
    },
    {
        "app": 'Drone CI', "category": 'CI/CD-Server / Container-native Pipelines',
        "risk": 'HIGH', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": ['set-cookie: _session_='],
        "body_markers": ['window.DRONE_'],
        "login_paths": ['/login', '/account/token'],
        "exposure_checks": [{'path': '/version', 'status': 200, 'body_contains': ['"version"', '"source"'], 'proves': 'Drone server /version answers without auth, confirming a Drone CI instance and its version.', 'risk': 'INFO'}, {'path': '/healthz', 'status': 200, 'body_contains': ['"ok"'], 'proves': 'Drone server health (DB ping) answers anonymously, confirming a reachable, running Drone backend.', 'risk': 'INFO'}],
    },
    {
        "app": 'Emby', "category": 'Media server (streaming)',
        "risk": 'INFO', "intended_public": True,
        "titles": ['emby'],
        "servers": [],
        "headers": ['x-emby-authorization', 'x-emby-token'],
        "body_markers": ['application-name" content="emby', 'energize your media'],
        "login_paths": ['/web/index.html', '/System/Info/Public'],
        "exposure_checks": [{'path': '/System/Info/Public', 'status': 200, 'body_contains': ['"servername"', '"version"', '"id"', '"operatingsystem"'], 'proves': 'Unauthenticated public system info confirms a reachable Emby server and leaks server name, version, server Id and OS without any auth. (Also reachable under /emby/System/Info/Public.)', 'risk': 'LOW'}, {'path': '/System/Info/Public', 'status': 200, 'body_contains': ['"servername"', '"version"', '"startupwizardcompleted":false'], 'proves': 'StartupWizardCompleted=false indicates the Emby first-run wizard is still open, allowing an unauthenticated user to complete setup and seize the admin account.', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Forgejo', "category": 'Git-Forge / Source-Code-Hosting (Gitea-Fork)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['powered by forgejo'],
        "servers": [],
        "headers": [],
        "body_markers": ['powered by forgejo'],
        "login_paths": ['/user/login', '/user/sign_up', '/explore/repos'],
        "exposure_checks": [{'path': '/api/v1/version', 'status': 200, 'body_contains': ['"version"'], 'proves': 'Forgejo (Gitea-compatible) REST API answers anonymously by default, confirming the instance and leaking the version for CVE matching.', 'risk': 'LOW'}, {'path': '/api/v1/repos/search?limit=1', 'status': 200, 'body_contains': ['"ok":true', '"data"'], 'proves': 'Unauthenticated repo search returns the public repository index, proving anonymous browsing is enabled.', 'risk': 'MEDIUM'}, {'path': '/v2/', 'status': 200, 'body_contains': ['docker-distribution-api-version'], 'proves': 'Built-in container registry (shared Gitea impl) is reachable; discovery endpoint responds even when sign-in is enforced, so this only fingerprints registry presence rather than proving the CVE-2026-27771 private-image exposure.', 'risk': 'INFO'}],
    },
    {
        "app": 'Gitea', "category": 'Git-Forge / Source-Code-Hosting',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['powered by gitea'],
        "servers": [],
        "headers": ['set-cookie: i_like_gitea='],
        "body_markers": ['powered by gitea', 'i_like_gitea'],
        "login_paths": ['/user/login', '/user/sign_up', '/explore/repos'],
        "exposure_checks": [{'path': '/api/v1/version', 'status': 200, 'body_contains': ['"version"'], 'proves': 'Gitea REST API answers anonymously (default REQUIRE_SIGNIN_VIEW=false), confirming a Gitea instance and leaking the exact server version for CVE matching (e.g. <1.26.2 vulnerable to CVE-2026-27771).', 'risk': 'LOW'}, {'path': '/api/v1/repos/search?limit=1', 'status': 200, 'body_contains': ['"ok":true', '"data"'], 'proves': 'Unauthenticated repo search returns the public repository index, proving anonymous browsing is enabled and enumerating hosted repositories.', 'risk': 'MEDIUM'}, {'path': '/v2/', 'status': 200, 'body_contains': ['docker-distribution-api-version'], 'proves': "Built-in OCI/container registry is reachable; the discovery endpoint responds even when sign-in is required, so this only fingerprints the registry's presence. Confirming the actual CVE-2026-27771 anonymous-private-pull requires fetching a private manifest, which this endpoint does not prove.", 'risk': 'INFO'}],
    },
    {
        "app": 'GitLab', "category": 'Git-Forge / DevOps-Plattform',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['sign in · gitlab'],
        "servers": ['gitlab-workhorse'],
        "headers": ['set-cookie: _gitlab_session=', 'set-cookie: known_sign_in='],
        "body_markers": ['data-page="sessions', '/users/sign_in', 'gon.', 'content="GitLab"'],
        "login_paths": ['/users/sign_in', '/users/password/new', '/admin', '/-/profile'],
        "exposure_checks": [{'path': '/users/sign_up', 'status': 200, 'body_contains': ['new_user[username]', 'new_user[email]'], 'proves': 'Self-registration form is served (HTTP 200) instead of redirecting to /users/sign_in, proving open signup is enabled so anyone can create an account on the instance without invitation.', 'risk': 'HIGH'}, {'path': '/api/v4/projects?per_page=1', 'status': 200, 'body_contains': ['"path_with_namespace"', '"visibility"'], 'proves': 'The GitLab API returns the project list to an anonymous client, enumerating public/internal projects (and their namespaces) without authentication.', 'risk': 'MEDIUM'}, {'path': '/-/manifest.json', 'status': 200, 'body_contains': ['gitlab'], 'proves': 'Unauthenticated PWA manifest confirms the host is a GitLab instance even before login.', 'risk': 'INFO'}],
    },
    {
        "app": 'Grafana', "category": 'Metrics-Visualisierung / Dashboards',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['grafana'],
        "servers": [],
        "headers": ['x-frame-options: deny'],
        "body_markers": ['window.grafanaBootData', 'grafana_mask_icon.svg', '__grafana_app_bundle_loaded', 'frontend_boot_css_time_seconds', '/public/build/grafana'],
        "login_paths": ['/login', '/api/health'],
        "exposure_checks": [{'path': '/api/health', 'status': 200, 'body_contains': ['"database"', '"version"', '"commit"'], 'proves': "Grafana's /api/health requires no auth in any configuration; the JSON confirms the app identity and leaks the exact Grafana version and commit, useful for targeting known CVEs.", 'risk': 'LOW'}, {'path': '/api/frontend/settings', 'status': 200, 'body_contains': ['"buildinfo"', '"appsuburl"', '"datasources"'], 'proves': 'Unauthenticated frontend settings reveal build/version, configured datasource names and auth options (e.g. anonymous/signup enabled), confirming an exposed and information-leaking Grafana instance.', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'HashiCorp Vault', "category": 'Secrets-Management / Zentraler Secret-Store',
        "risk": 'HIGH', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": [],
        "body_markers": ['id="ember-app"', '{{rootURL}}', 'data-app-boot', '/ui/vault/auth'],
        "login_paths": ['/ui/', '/ui/vault/auth', '/v1/sys/health', '/v1/sys/seal-status'],
        "exposure_checks": [{'path': '/v1/sys/seal-status', 'status': 200, 'body_contains': ['"sealed"', '"initialized"'], 'proves': "Vault's unauthenticated seal-status confirms a Vault instance and discloses version, seal/unseal state, key-share threshold (t/n) and storage type for targeting.", 'risk': 'LOW'}, {'path': '/v1/sys/init', 'status': 200, 'body_contains': ['"initialized":false'], 'proves': 'GET /v1/sys/init returns 200 unauthenticated with initialized=false, signalling an UNINITIALIZED Vault where an anonymous caller can PUT /v1/sys/init to generate and capture the root token + unseal keys (full secrets takeover). Note: /v1/sys/health returns 501 (not 200) when uninitialized by default, so seal-status/init are the reliable signals.', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Heimdall', "category": 'Application-Dashboard / Launcher',
        "risk": 'LOW', "intended_public": False,
        "titles": ['heimdall'],
        "servers": [],
        "headers": ['set-cookie: heimdall_session'],
        "body_markers": ['img/heimdall-logo-small.svg'],
        "login_paths": ['/', '/userselect'],
        "exposure_checks": [{'path': '/', 'status': 200, 'body_contains': ['dashboarditems', 'app-pin', 'heimdall'], 'proves': "Heimdall has no built-in authentication; a dashboard root containing Heimdall's distinctive markup confirms an exposed instance whose configured app links and internal URLs are visible to anyone.", 'risk': 'LOW'}],
    },
    {
        "app": 'Homarr', "category": 'Application-Dashboard',
        "risk": 'LOW', "intended_public": False,
        "titles": ['homarr'],
        "servers": [],
        "headers": [],
        "body_markers": [],
        "login_paths": ['/init', '/login', '/auth/login'],
        "exposure_checks": [{'path': '/api/trpc/integration.all?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D', 'status': 200, 'body_contains': ['"result"', '"url"', '"kind"'], 'proves': "Homarr's integration.all tRPC route is a publicProcedure (CVE-2026-27796 / GHSA-m4vc-4prp-cvp7, fixed in 1.54.0); an unauth response lists all configured integrations with internal URLs and types, confirming the app and leaking topology.", 'risk': 'MEDIUM'}, {'path': '/onboard', 'status': 200, 'body_contains': ['onboarding', 'create administrator', 'external-group'], 'proves': 'Homarr forces creation of an irremovable admin during first-run onboarding; a reachable /onboard page means setup is not finished and an unauthenticated attacker can create the admin account for full takeover.', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Home Assistant', "category": 'Home-Automation / IoT-Dashboard',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['home assistant'],
        "servers": [],
        "headers": [],
        "body_markers": ['<home-assistant>', '</home-assistant>', '/frontend_latest/', '/static/icons/favicon-192x192.png', 'ha-authorize', 'await import(`${'],
        "login_paths": ['/', '/auth/authorize', '/onboarding.html'],
        "exposure_checks": [{'path': '/api/onboarding', 'status': 200, 'body_contains': ['"step": "user"', '"done": false'], 'proves': 'Die Onboarding-API ist unauth abrufbar und der \'user\'-Schritt ist NICHT erledigt ("done": false) → frische, nicht initialisierte HA-Instanz. Ein unauth Angreifer kann via POST /api/onboarding/users den ersten Admin-Account anlegen (vollstaendiger Account-/Instanz-Takeover). "done": false auf dem user-Schritt ist der entscheidende Takeover-Indikator; bei bereits initialisierten Instanzen ist dieser Schritt done=true.', 'risk': 'CRITICAL'}, {'path': '/manifest.json', 'status': 200, 'body_contains': ['"name": "home assistant"', 'start_url'], 'proves': 'Unauth abrufbares Web-App-Manifest identifiziert die Instanz eindeutig als Home Assistant (App-Fingerprint, keine Exposition sensibler Daten).', 'risk': 'INFO'}],
    },
    {
        "app": 'Homepage', "category": 'Application-Dashboard / Startpage',
        "risk": 'LOW', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": [],
        "body_markers": ['A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations'],
        "login_paths": ['/'],
        "exposure_checks": [{'path': '/api/healthcheck', 'status': 200, 'body_contains': ['"status"', '"uptime"'], 'proves': 'gethomepage Homepage ships with no auth by design; a reachable healthcheck JSON confirms an exposed Homepage instance whose dashboard proxies privileged service API keys to any visitor.', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'Immich', "category": 'Foto-/Video-Verwaltung (self-hosted)',
        "risk": 'INFO', "intended_public": True,
        "titles": ['immich'],
        "servers": [],
        "headers": [],
        "body_markers": ['immich-ui-theme'],
        "login_paths": ['/auth/login', '/api/server/config', '/api/server/about', '/api/server/version', '/api/server/ping', '/api/server-info/ping'],
        "exposure_checks": [{'path': '/api/server/config', 'status': 200, 'body_contains': ['"isinitialized"', '"isonboarded"', '"oauthbuttontext"', '"loginpagemessage"'], 'proves': 'ServerConfigDto is served by the @Public() /server/config route; receiving these fields without auth confirms an exposed Immich instance and leaks deployment config (OAuth settings, login message, trash/delete delays).', 'risk': 'LOW'}, {'path': '/api/server/config', 'status': 200, 'body_contains': ['"isinitialized":false', '"isonboarded"'], 'proves': 'isInitialized=false means no admin account exists yet; anyone can call POST /api/auth/admin-sign-up to create the first (admin) account (unauthenticated admin takeover, ref. immich issue #24479).', 'risk': 'CRITICAL'}, {'path': '/api/server/version', 'status': 200, 'body_contains': ['"major"', '"minor"', '"patch"'], 'proves': 'The public /server/version route returns the exact Immich version unauthenticated, confirming the app and enabling version-targeted exploitation.', 'risk': 'INFO'}],
    },
    {
        "app": 'Jellyfin', "category": 'Media server (streaming)',
        "risk": 'INFO', "intended_public": True,
        "titles": ['jellyfin'],
        "servers": [],
        "headers": ['x-emby-authorization', 'x-emby-token'],
        "body_markers": ['application-name" content="jellyfin', '@jellyfin/ux-web'],
        "login_paths": ['/web/index.html', '/System/Info/Public', '/web/#/login.html', '/web/#/wizardstart.html'],
        "exposure_checks": [{'path': '/System/Info/Public', 'status': 200, 'body_contains': ['"productname":"jellyfin server"', '"version"', '"startupwizardcompleted"'], 'proves': 'Unauthenticated public system info confirms a reachable Jellyfin server and leaks server name, exact version and server Id without any auth.', 'risk': 'LOW'}, {'path': '/System/Info/Public', 'status': 200, 'body_contains': ['"productname":"jellyfin server"', '"startupwizardcompleted":false'], 'proves': 'StartupWizardCompleted=false means the first-run setup wizard is still open; an unauthenticated visitor can drive /Startup/* to complete setup and create the admin account (account takeover).', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Jenkins', "category": 'CI/CD-Server / Build-Automation',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['sign in [jenkins]', 'dashboard [jenkins]'],
        "servers": ['jetty', 'winstone'],
        "headers": ['x-jenkins:', 'x-hudson:', 'x-jenkins-session:', 'x-hudson-cli-port:', 'x-jenkins-cli-port:', 'x-jenkins-cli2-port:'],
        "body_markers": ['jenkins-name-icon', 'data-rooturl', '/adjuncts/', 'resURL', '/login?from='],
        "login_paths": ['/login', '/manage', '/script', '/asynchPeople/'],
        "exposure_checks": [{'path': '/api/json', 'status': 200, 'body_contains': ['"jobs"', '"_class"'], 'proves': 'The Jenkins REST API returns job/build data to an anonymous client, proving anonymous read access is enabled (or no security realm configured) and exposing the CI job inventory. This is not the default of the setup wizard, so a 200 here indicates a real misconfiguration.', 'risk': 'HIGH'}, {'path': '/script', 'status': 200, 'body_contains': ['script console', 'groovy'], 'proves': 'The Groovy Script Console is reachable unauthenticated, granting arbitrary code execution (RCE) on the Jenkins controller.', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Keycloak', "category": 'IdP / SSO (Identity & Access Management)',
        "risk": 'HIGH', "intended_public": True,
        "titles": ['sign in to keycloak'],
        "servers": [],
        "headers": ['set-cookie: kc_restart', 'set-cookie: auth_session_id'],
        "body_markers": ['kc-form-login', 'kc-header-wrapper', 'login-pf', 'data-page-id="login-'],
        "login_paths": ['/realms/master/.well-known/openid-configuration', '/admin/master/console/', '/realms/master/protocol/openid-connect/auth'],
        "exposure_checks": [{'path': '/realms/master', 'status': 200, 'body_contains': ['"realm":"master"', '"public_key"', '"token-service"'], 'proves': 'The realm info endpoint (public by OIDC design) returns the master-realm name, signing public_key and token-service URL with no auth, fingerprinting an exposed Keycloak and revealing realm/endpoint metadata; not protected data but a useful identification/info leak.', 'risk': 'LOW'}, {'path': '/realms/master/.well-known/openid-configuration', 'status': 200, 'body_contains': ['"issuer"', '"token_endpoint"', '"jwks_uri"'], 'proves': "The unauthenticated OIDC discovery document enumerates Keycloak's issuer and all OAuth/OIDC endpoints, confirming the IdP is reachable and exposing its configuration surface.", 'risk': 'INFO'}],
    },
    {
        "app": 'Komodo', "category": 'Build & deployment / container management platform',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['komodo'],
        "servers": [],
        "headers": [],
        "body_markers": ['href="/favicon.svg"', '/favicon-96x96.png'],
        "login_paths": ['/login', '/auth/local/login', '/auth/local/create_user'],
        "exposure_checks": [{'path': '/auth/GetLoginOptions', 'status': 200, 'body_contains': ['"local"', '"oidc"', '"github"'], 'proves': 'Komodo Core answers the login-options API unauthenticated (the UI calls this to render the login page), fingerprinting the app and disclosing which auth methods (local password, GitHub, Google, OIDC) are enabled. If local registration is enabled, the Sign Up flow is reachable unauth.', 'risk': 'LOW'}],
    },
    {
        "app": 'Kubernetes Dashboard', "category": 'Kubernetes cluster web UI',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['kubernetes dashboard'],
        "servers": [],
        "headers": [],
        "body_markers": ['<kd-root>', 'assets/images/kubernetes-logo.png', 'assets/config/config.json'],
        "login_paths": ['/#/login', '/api/v1/login/status', '/api/v1/csrftoken/login'],
        "exposure_checks": [{'path': '/api/v1/login/status', 'status': 200, 'body_contains': ['tokenpresent', 'httpsmode'], 'proves': 'The Dashboard backend answers its login-status API unauthenticated with JSON, confirming an exposed Kubernetes Dashboard reachable over the network rather than only via kubectl proxy.', 'risk': 'MEDIUM'}, {'path': '/api/v1/namespace', 'status': 200, 'body_contains': ['listmeta', '"namespaces"'], 'proves': 'Returning actual namespace data without a bearer token proves skip-login/insecure mode is enabled with a privileged service account, allowing unauthenticated read (and likely write) of cluster resources.', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'MikroTik RouterOS (Webfig)', "category": 'Firewall / router admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['mikrotik routeros > administration', 'mikrotik routeros managing webpage'],
        "servers": ['mikrotik httpproxy'],
        "headers": ['server: mikrotik httpproxy'],
        "body_markers": ['if this device is not in your possession, please contact your local network administrator', '<img src="/webfig/', '<img src="/webcfg/', 'mikrotik routeros'],
        "login_paths": ['/', '/webfig/', '/login'],
    },
    {
        "app": 'Mongo Express', "category": 'DB-Admin (MongoDB)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['mongo express'],
        "servers": [],
        "headers": ['set-cookie: mongo-express='],
        "body_markers": ['mongo-express', '/public/css/style.css', 'Mongo Express'],
        "login_paths": ['/', '/mongo-express/'],
        "exposure_checks": [{'path': '/', 'status': 200, 'body_contains': ['mongo express', 'databases', '/db/admin'], 'proves': "Mongo-Express ist im Default-Image mit Basic-Auth (admin/pass) gehaertet und liefert dann 401. Eine 200-Antwort mit der DB-Liste (Navbar-Brand 'mongo express', Datenbank-Tabelle mit /db/<name>-Links wie /db/admin) beweist, dass Basic-Auth deaktiviert/leer gesetzt wurde → voller unauth MongoDB-Admin-Zugriff inkl. Drop. Die 401-Seite enthaelt keinen dieser Body-Marker.", 'risk': 'CRITICAL'}],
    },
    {
        "app": 'n8n', "category": 'Workflow-Automation / Low-Code (selbstgehostet)',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['n8n'],
        "servers": [],
        "headers": ['set-cookie: n8n-auth='],
        "body_markers": ['window.BASE_PATH', '/rest/login', 'n8n-auth'],
        "login_paths": ['/signin', '/setup', '/rest/login'],
        "exposure_checks": [{'path': '/rest/settings', 'status': 200, 'body_contains': ['"showsetuponfirstload":true'], 'proves': 'n8n owner account is NOT yet created: anyone reaching this instance can register as the instance owner via /rest/owner/setup, taking full admin control (account takeover).', 'risk': 'CRITICAL'}, {'path': '/rest/settings', 'status': 200, 'body_contains': ['"endpointwebhook"', '"instanceid"'], 'proves': 'n8n frontend settings API answers without auth, confirming an n8n automation instance and leaking instance config (instanceId, webhook/endpoint paths, enabled features) for reconnaissance.', 'risk': 'LOW'}],
    },
    {
        "app": 'Netdata', "category": 'Echtzeit-System-/Performance-Monitoring',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['netdata'],
        "servers": ['netdata embedded http server'],
        "headers": ['server: netdata embedded http server'],
        "body_markers": [],
        "login_paths": ['/', '/api/v1/info', '/api/v1/charts'],
        "exposure_checks": [{'path': '/api/v1/info', 'status': 200, 'body_contains': ['"mirrored_hosts"', '"os_name"', '"version"'], 'proves': 'Pre-v2 Netdata agents expose the dashboard and v1 API anonymously by default; an unauth info response leaks host inventory, OS, version and collectors, confirming an exposed Netdata agent (v2+ requires sign-in by default).', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'Nextcloud', "category": 'Datei-/Collaboration-Plattform',
        "risk": 'INFO', "intended_public": True,
        "titles": ['nextcloud'],
        "servers": [],
        "headers": ['oc_sessionpassphrase', 'nc_samesitecookielax', 'nc_samesitecookiestrict'],
        "body_markers": ['data-requesttoken', 'id="body-login"', 'id="body-public"'],
        "login_paths": ['/login', '/index.php/login', '/status.php', '/ocs/v2.php/cloud/capabilities'],
        "exposure_checks": [{'path': '/status.php', 'status': 200, 'body_contains': ['"installed":true', '"version"', '"versionstring"', '"edition"'], 'proves': 'status.php is public by default and returns JSON without auth; the version/versionstring/edition fields confirm an exposed Nextcloud and leak the exact server version for CVE matching.', 'risk': 'LOW'}, {'path': '/status.php', 'status': 200, 'body_contains': ['"installed":false', '"maintenance":false', '"productname"'], 'proves': 'installed=false means the installation wizard has not run; an unauthenticated visitor can complete the wizard and create the admin account (full account/instance takeover).', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Nginx Proxy Manager', "category": 'Reverse-Proxy-Admin',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['nginx proxy manager'],
        "servers": ['openresty'],
        "headers": ['x-served-by: nginx-proxy-manager'],
        "body_markers": ['nginx proxy manager'],
        "login_paths": ['/login', '/api/tokens', '/api/schema'],
        "exposure_checks": [{'path': '/api/', 'status': 200, 'body_contains': ['"version"', '"major"', '"revision"'], 'proves': 'The NPM backend root endpoint is in the public (no-auth) tag and returns its version object unauthenticated, confirming an exposed Nginx Proxy Manager admin API.', 'risk': 'LOW'}, {'path': '/api/', 'status': 200, 'body_contains': ['"setup":true'], 'proves': 'NPM reports setup:true at the unauth root endpoint, meaning no admin user exists yet; the setup flow lets anyone create the first administrator account (unauth account takeover).', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Node-RED', "category": 'Flow-Automation / IoT-Orchestrierung',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['node-red'],
        "servers": [],
        "headers": [],
        "body_markers": ['red/red.min.js', 'vendor/vendor.js', 'red/main.min.js', 'id="red-ui-editor"', 'RED.init'],
        "login_paths": ['/', '/auth/login', '/red/'],
        "exposure_checks": [{'path': '/settings', 'status': 200, 'body_contains': ['"httpnoderoot"', '"version"'], 'proves': 'Node-RED admin API responds without auth, proving adminAuth is not configured (the default): the flow editor and Admin API are fully open, allowing flow modification and arbitrary code execution via function nodes.', 'risk': 'CRITICAL'}, {'path': '/flows', 'status': 200, 'body_contains': ['"type":"tab"'], 'proves': 'Full flow definitions are returned unauthenticated, leaking automation logic plus embedded credentials/config and confirming the unprotected Admin API.', 'risk': 'HIGH'}],
    },
    {
        "app": 'OpenWrt LuCI', "category": 'Firewall / router admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['openwrt', 'luci - lua configuration interface'],
        "servers": [],
        "headers": [],
        "body_markers": ['powered by luci', '/cgi-bin/luci', '/luci-static/', '/luci-static/bootstrap/', '/luci-static/resources/'],
        "login_paths": ['/cgi-bin/luci', '/cgi-bin/luci/', '/'],
        "exposure_checks": [{'path': '/cgi-bin/luci/', 'status': 200, 'body_contains': ['powered by luci', 'openwrt'], 'proves': "The LuCI login page is reachable unauthenticated and its page footer leaks the exact LuCI/OpenWrt build banner (e.g. 'Powered by LuCI ... OpenWrt SNAPSHOT r...'), disclosing the router admin UI and its precise firmware version without credentials.", 'risk': 'LOW'}],
    },
    {
        "app": 'OPNsense', "category": 'Firewall / router admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['| opnsense'],
        "servers": ['opnsense'],
        "headers": ['server: opnsense'],
        "body_markers": ['/ui/themes/opnsense/', 'login_message'],
        "login_paths": ['/', '/index.php', '/ui/'],
    },
    {
        "app": 'Paperless-ngx', "category": 'Dokumenten-Management (DMS)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['paperless-ngx'],
        "servers": [],
        "headers": [],
        "body_markers": ['<pngx-root', '</pngx-root>'],
        "login_paths": ['/accounts/login/', '/api/', '/api/ui_settings/'],
    },
    {
        "app": 'pfSense', "category": 'Firewall / router admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['pfsense - login'],
        "servers": [],
        "headers": [],
        "body_markers": ['csrfmagicname = "__csrf_magic"', '/csrf/csrf-magic.js', '/js/pfsense.js', "name='__csrf_magic'"],
        "login_paths": ['/', '/index.php'],
    },
    {
        "app": 'pgAdmin', "category": 'DB-Admin (PostgreSQL)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['pgadmin 4'],
        "servers": [],
        "headers": ['set-cookie: pga4_session'],
        "body_markers": ['/pgadmin4/static/', 'id="standard_login"', 'PGADMIN_LANGUAGE', 'pgadmin4/static/js/generated'],
        "login_paths": ['/login', '/pgadmin4/login'],
        "exposure_checks": [{'path': '/browser/', 'status': 200, 'body_contains': ['pgadmin', 'require.js', 'pgadmin.browser'], 'proves': 'Der pgAdmin4-Browser/Workspace (require.js-Bootstrap mit pgadmin.browser) wird OHNE Redirect auf /login direkt ausgeliefert → die Instanz ist im DESKTOP-/Server-Mode ohne erzwungenes Login erreichbar (oder Auth deaktiviert), wodurch ein unauth Angreifer Datenbankverbindungen einsehen/nutzen kann. Eine login-geschuetzte Instanz wuerde hier 302 auf /login liefern, nicht 200 mit dem Browser-Bootstrap.', 'risk': 'HIGH'}],
    },
    {
        "app": 'phpMyAdmin', "category": 'DB-Admin (MySQL/MariaDB)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['phpmyadmin'],
        "servers": [],
        "headers": ['set-cookie: phpMyAdmin=', 'set-cookie: pma_lang=', 'set-cookie: pmaUser-', 'set-cookie: pmaAuth-'],
        "body_markers": ['pma_username', 'pma_password', 'phpmyadmin.css.php', 'themes/pmahomme', 'js/messages.php', 'pmaThemesImage', 'token=', '#pma_navigation'],
        "login_paths": ['/', '/index.php', '/phpmyadmin/', '/phpmyadmin/index.php'],
        "exposure_checks": [{'path': '/index.php?db=information_schema', 'status': 200, 'body_contains': ["var db = 'information_schema'", 'db_structure.php', 'table_structure.php'], 'proves': "phpMyAdmin liefert die DB-Oberflaeche (information_schema) OHNE Login-Formular zurueck — config-/no-password-Auth ist aktiv, jeder hat vollen DB-Admin-Zugriff (kein Passwort noetig). Die JS-Variable 'var db =' und die Navigations-Links db_structure.php/table_structure.php erscheinen ausschliesslich auf der eingeloggten DB-Ansicht, NICHT auf der Login-Seite.", 'risk': 'CRITICAL'}, {'path': '/phpmyadmin/index.php?db=information_schema', 'status': 200, 'body_contains': ["var db = 'information_schema'", 'db_structure.php', 'table_structure.php'], 'proves': 'Wie oben, aber unter dem ueblichen /phpmyadmin/ Subpfad: offene phpMyAdmin-Instanz mit auto-/passwortlosem Login. FP-arm, da die Login-Seite genau diese eingeloggten DB-Ansicht-Marker (var db, db_structure.php) nicht enthaelt.', 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Pi-hole', "category": 'DNS-Adblocker (Netzwerk-Admin)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['pi-hole'],
        "servers": ['lighttpd'],
        "headers": ['x-pi-hole', 'x-frame-options: deny'],
        "body_markers": ['a black hole for internet advertisements', 'x-pi-hole', 'pi-hole, llc'],
        "login_paths": ['/admin/login.php', '/admin/login', '/admin/index.php', '/api/auth'],
        "exposure_checks": [{'path': '/api/auth', 'status': 200, 'body_contains': ['no password set', '"valid":true'], 'proves': "Pi-hole v6 API responds with 'no password set' / valid:true, meaning the admin interface has no password and all admin/config API endpoints are usable fully unauthenticated.", 'risk': 'CRITICAL'}, {'path': '/admin/api.php?versions', 'status': 200, 'body_contains': ['core_current', 'ftl_current', 'web_current'], 'proves': 'The legacy v5 API returns Pi-hole core/FTL/web version data without auth (works when no admin password is set), confirming an exposed and unprotected Pi-hole.', 'risk': 'LOW'}],
    },
    {
        "app": 'Plex', "category": 'Media server (streaming)',
        "risk": 'INFO', "intended_public": True,
        "titles": ['plex'],
        "servers": [],
        "headers": ['x-plex-protocol', 'x-plex-content-original-length', 'x-plex-content-compressed-length'],
        "body_markers": ['<mediacontainer'],
        "login_paths": ['/identity', '/web/index.html'],
        "exposure_checks": [{'path': '/identity', 'status': 200, 'body_contains': ['<mediacontainer', 'machineidentifier=', 'version='], 'proves': 'The /identity endpoint requires no X-Plex-Token; a valid MediaContainer with machineIdentifier and version confirms an exposed Plex Media Server and leaks its unique machine id and exact version.', 'risk': 'LOW'}, {'path': '/identity', 'status': 200, 'body_contains': ['<mediacontainer', 'machineidentifier=', 'claimed="0"'], 'proves': 'claimed="0" means the server has never been claimed by a Plex account; an unauthenticated attacker who can reach it can claim it and take over administration.', 'risk': 'HIGH'}],
    },
    {
        "app": 'Portainer', "category": 'Container management UI (Docker/Swarm/K8s)',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['portainer'],
        "servers": [],
        "headers": [],
        "body_markers": ['ng-app="portainer"', 'assets/ico/safari-pinned-tab.svg', 'assets/ico/browserconfig.xml'],
        "login_paths": ['/#!/auth', '/#!/init/admin', '/api/system/status'],
        "exposure_checks": [{'path': '/api/users/admin/check', 'status': 404, 'body_contains': ['no administrator account found'], 'proves': 'A 404 here means no admin account exists yet, so /api/users/admin/init can be POSTed unauthenticated to create the first admin and fully take over the Portainer instance (initial-setup window).', 'risk': 'CRITICAL'}, {'path': '/api/system/status', 'status': 200, 'body_contains': ['version', 'instanceid'], 'proves': 'Returns Portainer version and instance ID without authentication, fingerprinting the app and leaking build/version info usable for targeting known CVEs.', 'risk': 'LOW'}],
    },
    {
        "app": 'Prometheus', "category": 'Metrics-Datenbank / TSDB',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['prometheus time series collection and processing server'],
        "servers": [],
        "headers": [],
        "body_markers": ['GLOBAL_AGENT_MODE', 'GLOBAL_CONSOLES_LINK', 'PATH_PREFIX_PLACEHOLDER', '/classic/static/'],
        "login_paths": ['/graph', '/-/healthy', '/-/ready', '/api/v1/status/buildinfo', '/api/v1/status/config'],
        "exposure_checks": [{'path': '/api/v1/status/buildinfo', 'status': 200, 'body_contains': ['"status":"success"', '"goversion"', '"revision"'], 'proves': 'Prometheus ships with no auth by default; a successful buildinfo response proves the TSDB API is reachable unauthenticated, exposing version and enabling full unauth query/metrics access.', 'risk': 'MEDIUM'}, {'path': '/api/v1/status/flags', 'status': 200, 'body_contains': ['"status":"success"', 'storage.tsdb.path', 'web.listen-address'], 'proves': 'The flags endpoint returns the live server configuration (storage paths, listen address, retention) with no auth, confirming an openly exposed Prometheus server.', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'Prowlarr', "category": 'Media-Automation (Indexer-Manager)',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['prowlarr'],
        "servers": [],
        "headers": [],
        "body_markers": ['window.prowlarr'],
        "login_paths": ['/login', '/initialize.json', '/initialize.js', '/api/v1/system/status', '/ping'],
    },
    {
        "app": 'Proxmox VE', "category": 'Hypervisor / virtualization admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['proxmox virtual environment'],
        "servers": [],
        "headers": ['set-cookie: pveauthcookie', 'csrfpreventiontoken'],
        "body_markers": ['pvemanagerlib.js', 'proxmoxlib.js', "auth_cookie_name: 'pveauthcookie'", 'pve.stdworkspace', '/pve2/ext6/', '/pve2/css/ext6-pve.css'],
        "login_paths": ['/', '/#login', '/api2/json/access/ticket'],
    },
    {
        "app": 'qBittorrent Web', "category": 'Torrent-Client (WebUI)',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['qbittorrent web ui'],
        "servers": [],
        "headers": ['set-cookie: sid='],
        "body_markers": ['icons/qbittorrent-tray.svg', 'images/qbittorrent-tray.svg'],
        "login_paths": ['/login.html', '/api/v2/app/version', '/api/v2/auth/login'],
        "exposure_checks": [{'path': '/api/v2/app/preferences', 'status': 200, 'body_contains': ['"save_path"', '"web_ui_username"', '"dht"'], 'proves': "qBittorrent's API normally requires auth; a 200 JSON preferences dump means 'Bypass authentication for clients on localhost/whitelisted subnets' is misconfigured-on, leaking the full config (paths, WebUI username, network settings) to unauthenticated callers.", 'risk': 'HIGH'}, {'path': '/api/v2/app/version', 'status': 200, 'body_contains': ['v4.', 'v5.'], 'proves': 'All qBittorrent API methods except /auth/login require auth; an unauthenticated 200 returning a version string (instead of 403/Forbidden) confirms a WebUI with auth-bypass enabled and leaks the exact client version.', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'Radarr', "category": 'Media-Automation (PVR, Filme)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['radarr'],
        "servers": [],
        "headers": [],
        "body_markers": ['window.radarr'],
        "login_paths": ['/login', '/initialize.json', '/initialize.js', '/api/v3/system/status', '/ping'],
    },
    {
        "app": 'Rancher', "category": 'Kubernetes multi-cluster management platform',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['rancher'],
        "servers": [],
        "headers": ['set-cookie: r_sess=', 'x-api-cattle'],
        "body_markers": ['href="/favicon.png"', 'r_theme', 'r_pcs'],
        "login_paths": ['/dashboard/auth/login', '/v3-public/authProviders'],
        "exposure_checks": [{'path': '/v3/settings/cacerts', 'status': 200, 'body_contains': ['"name":"cacerts"', 'basetype', 'setting'], 'proves': 'Rancher serves the cacerts setting publicly without authentication; reachability confirms a Rancher management server and can leak the internal CA certificate used by downstream cluster agents.', 'risk': 'MEDIUM'}, {'path': '/v3-public/authProviders', 'status': 200, 'body_contains': ['authprovidercollection', 'localprovider'], 'proves': 'The /v3-public auth-providers collection is returned unauthenticated by design, fingerprinting Rancher and disclosing which authentication backends (local, AD, OIDC, etc.) are configured.', 'risk': 'LOW'}],
    },
    {
        "app": 'Redis Commander', "category": 'DB-Admin (Redis)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['redis commander'],
        "servers": [],
        "headers": [],
        "body_markers": ['redis-commander', 'ng-controller="navController"', '/scripts/', 'httpAuth'],
        "login_paths": ['/', '/sign-in'],
        "exposure_checks": [{'path': '/', 'status': 200, 'body_contains': ['redis commander', 'rediscommandlogo', 'disconnectall'], 'proves': "Redis Commander liefert die volle Management-UI direkt aus (Titel 'redis commander', Logo-Element rediscommandlogo, Toolbar-Aktion disconnectAll) ohne Sign-In-Formular. Bei leerem http-auth-Username (Default) ist KEINE UI-Authentifizierung aktiv → jeder hat Lese-/Schreibzugriff auf alle Redis-Keys.", 'risk': 'CRITICAL'}],
    },
    {
        "app": 'Seafile', "category": 'Datei-Sync/Sharing (self-hosted)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['seafile'],
        "servers": [],
        "headers": ['sfcsrftoken'],
        "body_markers": ['seafile-ui.css', 'static/scripts/lib/seafile-ui'],
        "login_paths": ['/accounts/login/', '/api2/server-info/', '/api2/ping/'],
        "exposure_checks": [{'path': '/api2/server-info/', 'status': 200, 'body_contains': ['"version"', '"encrypted_library_version"', '"features"'], 'proves': 'The anonymous /api2/server-info/ endpoint returns version and feature flags (e.g. seafile-pro) without auth, confirming an exposed Seafile server and leaking its exact version and edition.', 'risk': 'LOW'}],
    },
    {
        "app": 'Sonarr', "category": 'Media-Automation (PVR, TV)',
        "risk": 'MEDIUM', "intended_public": False,
        "titles": ['sonarr'],
        "servers": [],
        "headers": [],
        "body_markers": ['window.sonarr'],
        "login_paths": ['/login', '/initialize.json', '/initialize.js', '/api/v3/system/status', '/ping'],
    },
    {
        "app": 'Synology DSM', "category": 'NAS / storage admin',
        "risk": 'HIGH', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": ['set-cookie: id=', 'x-syno-', 'set-cookie: stay_login'],
        "body_markers": ['syno.sds', 'syno.core.desktop.sessiondata', 'synohdpack', '/webman/', 'synowstransporter', 'syno_finder'],
        "login_paths": ['/webman/index.cgi', '/', '/webapi/auth.cgi', '/#/signin'],
        "exposure_checks": [{'path': '/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=all', 'status': 200, 'body_contains': ['syno.api.auth', 'maxversion', '"success":true'], 'proves': 'SYNO.API.Info is the one DSM API that requires no authorization by design; an unauthenticated 200 with the API map (paths/min-maxVersion) proves a Synology DSM is exposed and enumerates its reachable API surface (info leak / attack-surface discovery).', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'Traefik Dashboard', "category": 'Reverse-Proxy-Admin',
        "risk": 'HIGH', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": [],
        "body_markers": ['faency', 'statics/css/faency'],
        "login_paths": ['/api/rawdata', '/api/overview', '/api/version', '/dashboard/'],
        "exposure_checks": [{'path': '/api/version', 'status': 200, 'body_contains': ['"version"', '"codename"'], 'proves': 'Reachable /api/version returns the Traefik build version with no auth, proving the API is running in api.insecure=true mode (auth is disabled by default this endpoint 404s).', 'risk': 'MEDIUM'}, {'path': '/api/rawdata', 'status': 200, 'body_contains': ['"routers"', '"services"', '"middlewares"'], 'proves': '/api/rawdata dumps the full dynamic configuration (routers, services, middlewares, backend URLs) without auth, leaking the entire internal topology and any inlined credentials.', 'risk': 'HIGH'}],
    },
    {
        "app": 'TrueNAS (CORE / SCALE)', "category": 'NAS / storage admin',
        "risk": 'HIGH', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": [],
        "body_markers": ['<ix-root', '</ix-root>', 'ix-dark', 'assets/favicons/site.webmanifest'],
        "login_paths": ['/', '/ui/sessions/signin', '/#/sessions/signin'],
    },
    {
        "app": 'Unraid', "category": 'NAS / storage admin',
        "risk": 'HIGH', "intended_public": False,
        "titles": [],
        "servers": [],
        "headers": ['set-cookie: unraid_'],
        "body_markers": ['/webgui/styles/', '/webgui/images/', 'case-model.cfg', 'dynamix.my.servers', 'docs.unraid.net/go/lost-root-password'],
        "login_paths": ['/login', '/Login', '/'],
    },
    {
        "app": 'Uptime Kuma', "category": 'Uptime-/Status-Monitoring',
        "risk": 'LOW', "intended_public": False,
        "titles": ['uptime kuma'],
        "servers": [],
        "headers": [],
        "body_markers": ['Uptime Kuma monitoring tool', '/icon.svg', '/upload/icon.svg'],
        "login_paths": ['/dashboard', '/setup'],
        "exposure_checks": [{'path': '/api/status-page/heartbeat/default', 'status': 200, 'body_contains': ['"heartbeatlist"', '"uptimelist"'], 'proves': 'Uptime Kuma status pages are public/unauthenticated by design; the default-slug heartbeat API returning live monitor heartbeats and uptime confirms the instance and leaks monitored services and their status.', 'risk': 'LOW'}, {'path': '/api/status-page/default', 'status': 200, 'body_contains': ['"publicgrouplist"', '"monitorlist"'], 'proves': 'The status-page config API returns the page config and grouped monitor list unauthenticated, confirming Uptime Kuma and exposing internal service names/topology.', 'risk': 'LOW'}],
    },
    {
        "app": 'Vaultwarden', "category": 'Passwort-Manager / Secrets (Bitwarden-kompatibler Server)',
        "risk": 'INFO', "intended_public": True,
        "titles": ['vaultwarden'],
        "servers": ['rocket'],
        "headers": ['set-cookie: vw_'],
        "body_markers": ['/bwrs_static/', 'bwrs', 'vaultwarden'],
        "login_paths": ['/', '/#/login', '/admin', '/#/register', '/api/version'],
        "exposure_checks": [{'path': '/api/config', 'status': 200, 'body_contains': ['"object":"config"', '"version"', '"featurestates"'], 'proves': 'Unauth /api/config gibt echte Server-Config zurueck (object=config, version, gitHash, featureStates) → eindeutiger Vaultwarden-Fingerprint inkl. praezisem Versions-/Feature-Leak (erlaubt gezielte CVE-Zuordnung). Information-Disclosure ohne Auth, aber kein direkter Zugriff auf Vaults.', 'risk': 'MEDIUM'}],
    },
    {
        "app": 'VMware ESXi (Host Client)', "category": 'Hypervisor / virtualization admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['vmware esxi'],
        "servers": [],
        "headers": [],
        "body_markers": ['ng-app="esxuiapp"', 'esxuiapp', 'id_eesx_welcome', 'vmware host client'],
        "login_paths": ['/ui/', '/ui/#/login', '/'],
        "exposure_checks": [{'path': '/sdk/vimServiceVersions.xml', 'status': 200, 'body_contains': ['urn:vim25', '<namespaces', '<priorversions>'], 'proves': 'ESXi/vCenter SOAP SDK descriptor is served without authentication (this endpoint is reachable pre-auth by design), identifying the host as a VMware vSphere/ESXi endpoint and leaking the supported vim25 API/product version (e.g. 8.0.x), confirming the management plane is reachable.', 'risk': 'LOW'}],
    },
    {
        "app": 'XCP-ng / Xen Orchestra', "category": 'Hypervisor / virtualization admin',
        "risk": 'CRITICAL', "intended_public": False,
        "titles": ['xen orchestra'],
        "servers": [],
        "headers": [],
        "body_markers": ['id="xo-app"', 'javascript is required for xen orchestra!', 'xo-web'],
        "login_paths": ['/', '/signin', '/v6/', '/#/'],
    },
    {
        "app": 'Yacht', "category": 'Docker container management UI',
        "risk": 'HIGH', "intended_public": False,
        "titles": ['yacht'],
        "servers": [],
        "headers": [],
        "body_markers": ["yacht doesn't work properly without javascript", '/img/icons/favicon.ico'],
        "login_paths": ['/#/login', '/api/auth/jwt/login', '/openapi.json'],
        "exposure_checks": [{'path': '/openapi.json', 'status': 200, 'body_contains': ['openapi', '/auth/jwt/login', '"paths"'], 'proves': 'Yacht (FastAPI backend) exposes its auto-generated OpenAPI schema unauthenticated by default, fingerprinting the app and disclosing the full API surface and route map.', 'risk': 'LOW'}, {'path': '/docs', 'status': 200, 'body_contains': ['swagger-ui', 'openapi.json'], 'proves': 'Interactive Swagger UI is reachable without auth (FastAPI default), confirming an exposed Yacht API and exposing all endpoints for exploration.', 'risk': 'LOW'}],
    },
]
